[package]
name = "RustLens"
version = "0.1.0"
edition = "2021"
default-run = "RustLens"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
mime = "0.3"
bmp = "0.5"